import { ElementType } from './element-type.const';

export interface AutocastSkillDef {
  name: string;
  isMatk: boolean;
  isMelee: boolean;
  element: ElementType;
  hit: number;
  totalHit: number;
  formula: (params: { skillLevel: number; baseLevel: number; str?: number; int?: number }) => number;
}

export const AUTOCAST_SKILL_REGISTRY: Record<string, AutocastSkillDef> = {
  'Fire Bolt': {
    name: 'Fire Bolt',
    isMatk: true,
    isMelee: false,
    element: ElementType.Fire,
    hit: 1,
    totalHit: 1,
    formula: ({ skillLevel }) => skillLevel * 100,
  },
  'Cold Bolt': {
    name: 'Cold Bolt',
    isMatk: true,
    isMelee: false,
    element: ElementType.Water,
    hit: 1,
    totalHit: 1,
    formula: ({ skillLevel }) => skillLevel * 100,
  },
  'Lightening Bolt': {
    name: 'Lightening Bolt',
    isMatk: true,
    isMelee: false,
    element: ElementType.Wind,
    hit: 1,
    totalHit: 1,
    formula: ({ skillLevel }) => skillLevel * 100,
  },
  'Fire Ball': {
    name: 'Fire Ball',
    isMatk: true,
    isMelee: false,
    element: ElementType.Fire,
    hit: 1,
    totalHit: 1,
    formula: ({ skillLevel }) => 70 + skillLevel * 10,
  },
  'Soul Strike': {
    name: 'Soul Strike',
    isMatk: true,
    isMelee: false,
    element: ElementType.Ghost,
    hit: 1,
    totalHit: 1,
    formula: ({ skillLevel }) => {
      const hits = Math.floor((skillLevel + 1) / 2);
      return hits * 100;
    },
  },
  'Frost Nova': {
    name: 'Frost Nova',
    isMatk: true,
    isMelee: false,
    element: ElementType.Water,
    hit: 1,
    totalHit: 1,
    formula: ({ skillLevel }) => 110 + skillLevel * 10,
  },
  'Meteor Storm': {
    name: 'Meteor Storm',
    isMatk: true,
    isMelee: false,
    element: ElementType.Fire,
    hit: 2,
    totalHit: 2,
    formula: () => 125,
  },
  'Lord of Vermilion': {
    name: 'Lord of Vermilion',
    isMatk: true,
    isMelee: false,
    element: ElementType.Wind,
    hit: 1,
    totalHit: 4,
    formula: () => 250,
  },
  'Storm Gust': {
    name: 'Storm Gust',
    isMatk: true,
    isMelee: false,
    element: ElementType.Water,
    hit: 1,
    totalHit: 3,
    formula: () => 200,
  },
  'Jupitel Thunder': {
    name: 'Jupitel Thunder',
    isMatk: true,
    isMelee: false,
    element: ElementType.Wind,
    hit: 1,
    totalHit: 1,
    formula: ({ skillLevel }) => skillLevel * 100,
  },
  'Bash': {
    name: 'Bash',
    isMatk: false,
    isMelee: true,
    element: ElementType.Neutral,
    hit: 1,
    totalHit: 1,
    formula: ({ skillLevel }) => 100 + skillLevel * 30,
  },
  'Sonic Blow': {
    name: 'Sonic Blow',
    isMatk: false,
    isMelee: true,
    element: ElementType.Neutral,
    hit: 1,
    totalHit: 8,
    formula: ({ skillLevel }) => skillLevel * 50,
  },
  'Bowling Bash': {
    name: 'Bowling Bash',
    isMatk: false,
    isMelee: true,
    element: ElementType.Neutral,
    hit: 1,
    totalHit: 1,
    formula: ({ skillLevel }) => 100 + skillLevel * 40,
  },
  'Double Strafe': {
    name: 'Double Strafe',
    isMatk: false,
    isMelee: false,
    element: ElementType.Neutral,
    hit: 1,
    totalHit: 2,
    formula: ({ skillLevel }) => 90 + skillLevel * 10,
  },
  'Heal': {
    name: 'Heal',
    isMatk: true,
    isMelee: false,
    element: ElementType.Holy,
    hit: 1,
    totalHit: 1,
    formula: ({ skillLevel, baseLevel }) => skillLevel * 10 * (baseLevel / 100),
  },
  'Sonic Wave': {
    name: 'Sonic Wave',
    isMatk: false,
    isMelee: false,
    element: ElementType.Neutral,
    hit: 1,
    totalHit: 1,
    formula: ({ skillLevel, baseLevel }) => (1050 + skillLevel * 150) * (baseLevel / 100),
  },
  'Runic Explosion': {
    name: 'Runic Explosion',
    isMatk: false,
    isMelee: true,
    element: ElementType.Neutral,
    hit: 1,
    totalHit: 1,
    formula: ({ skillLevel, baseLevel, str }) => (skillLevel + (str || 0) / 8) * 140 * (baseLevel / 100),
  },
  'Earth Spike': {
    name: 'Earth Spike',
    isMatk: true,
    isMelee: false,
    element: ElementType.Earth,
    hit: 1,
    totalHit: 1,
    formula: ({ skillLevel }) => skillLevel * 100,
  },
  'Napalm Vulcan': {
    name: 'Napalm Vulcan',
    isMatk: true,
    isMelee: false,
    element: ElementType.Ghost,
    hit: 1,
    totalHit: 1,
    formula: ({ skillLevel, baseLevel }) => skillLevel * 70 * (baseLevel / 100),
  },
  'Psychic Wave': {
    name: 'Psychic Wave',
    isMatk: true,
    isMelee: false,
    element: ElementType.Neutral,
    hit: 1,
    totalHit: 1,
    formula: ({ skillLevel, baseLevel, int }) => (skillLevel * 70 + (int || 0) * 3) * (baseLevel / 100),
  },
  'Cross Impact': {
    name: 'Cross Impact',
    isMatk: false,
    isMelee: true,
    element: ElementType.Neutral,
    hit: 1,
    totalHit: 7,
    formula: ({ skillLevel, baseLevel }) => (1150 + skillLevel * 400) * (baseLevel / 100),
  },
  'Ignition Break': {
    name: 'Ignition Break',
    isMatk: false,
    isMelee: true,
    element: ElementType.Fire,
    hit: 1,
    totalHit: 1,
    formula: ({ skillLevel, baseLevel }) => skillLevel * 450 * (baseLevel / 100),
  },
  'Crimson Rock': {
    name: 'Crimson Rock',
    isMatk: true,
    isMelee: false,
    element: ElementType.Fire,
    hit: 1,
    totalHit: 1,
    formula: ({ skillLevel, baseLevel }) => (700 + skillLevel * 600) * (baseLevel / 100),
  },
  'Jack Frost': {
    name: 'Jack Frost',
    isMatk: true,
    isMelee: false,
    element: ElementType.Water,
    hit: 1,
    totalHit: 1,
    formula: ({ skillLevel, baseLevel }) => (800 + skillLevel * 500) * (baseLevel / 100),
  },
  'Chain Lightning': {
    name: 'Chain Lightning',
    isMatk: true,
    isMelee: false,
    element: ElementType.Wind,
    hit: 1,
    totalHit: 1,
    formula: ({ skillLevel, baseLevel }) => (500 + skillLevel * 100) * (baseLevel / 100),
  },
  'Earth Strain': {
    name: 'Earth Strain',
    isMatk: true,
    isMelee: false,
    element: ElementType.Earth,
    hit: 1,
    totalHit: 1,
    formula: ({ skillLevel, baseLevel }) => (1000 + skillLevel * 600) * (baseLevel / 100),
  },
  'Cart Tornado': {
    name: 'Cart Tornado',
    isMatk: false,
    isMelee: true,
    element: ElementType.Neutral,
    hit: 1,
    totalHit: 1,
    formula: ({ skillLevel }) => skillLevel * 200,
  },
  'Arrow Vulcan': {
    name: 'Arrow Vulcan',
    isMatk: false,
    isMelee: false,
    element: ElementType.Neutral,
    hit: 1,
    totalHit: 1,
    formula: ({ skillLevel, baseLevel }) => (skillLevel * 150 + 100) * (baseLevel / 100),
  },
  'Spread Shot': {
    name: 'Spread Shot',
    isMatk: false,
    isMelee: false,
    element: ElementType.Neutral,
    hit: 1,
    totalHit: 1,
    formula: ({ skillLevel }) => skillLevel * 200,
  },
  'Spiral Pierce': {
    name: 'Spiral Pierce',
    isMatk: false,
    isMelee: true,
    element: ElementType.Neutral,
    hit: 1,
    totalHit: 5,
    formula: ({ skillLevel }) => skillLevel * 50 + 150,
  },
  'Gloria Domini': {
    name: 'Gloria Domini',
    isMatk: false,
    isMelee: false,
    element: ElementType.Holy,
    hit: 1,
    totalHit: 1,
    formula: ({ skillLevel }) => skillLevel * 200,
  },
  'Judex': {
    name: 'Judex',
    isMatk: true,
    isMelee: false,
    element: ElementType.Holy,
    hit: 1,
    totalHit: 1,
    formula: ({ skillLevel, baseLevel }) => (skillLevel * 100 + 200) * (baseLevel / 100),
  },
};
