import { ElementType } from './element-type.const';

export interface AutocastSkillDef {
  name: string;
  isMatk: boolean;
  isMelee: boolean;
  element: ElementType | null;
  hit: number;
  totalHit: number;
  canCri?: boolean;
  criDmgPercentage?: number;
  /** If true, formula returns flat damage (not ATK%), only modified by element/race/size/class/def */
  isFixedDamage?: boolean;
  /** If set, skill level comes from this learned skill instead of the autocast entry level */
  linkedSkill?: string;
  formula: (params: { skillLevel: number; baseLevel: number; str?: number; int?: number; agi?: number }) => number;
}

export const AUTOCAST_SKILL_REGISTRY: Record<string, AutocastSkillDef> = {
  'MG_FIREBOLT': {
    name: 'MG_FIREBOLT',
    isMatk: true,
    isMelee: false,
    element: ElementType.Fire,
    hit: 1,
    totalHit: 1,
    formula: ({ skillLevel }) => skillLevel * 100,
  },
  'MG_COLDBOLT': {
    name: 'MG_COLDBOLT',
    isMatk: true,
    isMelee: false,
    element: ElementType.Water,
    hit: 1,
    totalHit: 1,
    formula: ({ skillLevel }) => skillLevel * 100,
  },
  'MG_LIGHTNINGBOLT': {
    name: 'MG_LIGHTNINGBOLT',
    isMatk: true,
    isMelee: false,
    element: ElementType.Wind,
    hit: 1,
    totalHit: 1,
    formula: ({ skillLevel }) => skillLevel * 100,
  },
  'MG_FIREBALL': {
    name: 'MG_FIREBALL',
    isMatk: true,
    isMelee: false,
    element: ElementType.Fire,
    hit: 1,
    totalHit: 1,
    formula: ({ skillLevel }) => 70 + skillLevel * 10,
  },
  'MG_SOULSTRIKE': {
    name: 'MG_SOULSTRIKE',
    isMatk: true,
    isMelee: false,
    element: ElementType.Ghost,
    hit: 1,
    totalHit: 1,
    formula: ({ skillLevel }) => {
      const hits = Math.floor((skillLevel + 1) / 2);
      return hits * 100;
    },
  },
  'WZ_FROSTNOVA': {
    name: 'WZ_FROSTNOVA',
    isMatk: true,
    isMelee: false,
    element: ElementType.Water,
    hit: 1,
    totalHit: 1,
    formula: ({ skillLevel }) => 110 + skillLevel * 10,
  },
  'WZ_METEOR': {
    name: 'WZ_METEOR',
    isMatk: true,
    isMelee: false,
    element: ElementType.Fire,
    hit: 2,
    totalHit: 2,
    formula: () => 125,
  },
  'WZ_VERMILION': {
    name: 'WZ_VERMILION',
    isMatk: true,
    isMelee: false,
    element: ElementType.Wind,
    hit: 1,
    totalHit: 4,
    formula: () => 250,
  },
  'WZ_STORMGUST': {
    name: 'WZ_STORMGUST',
    isMatk: true,
    isMelee: false,
    element: ElementType.Water,
    hit: 1,
    totalHit: 3,
    formula: () => 200,
  },
  'WZ_JUPITEL': {
    name: 'WZ_JUPITEL',
    isMatk: true,
    isMelee: false,
    element: ElementType.Wind,
    hit: 1,
    totalHit: 1,
    formula: ({ skillLevel }) => skillLevel * 100,
  },
  'SM_BASH': {
    name: 'SM_BASH',
    isMatk: false,
    isMelee: true,
    element: ElementType.Neutral,
    hit: 1,
    totalHit: 1,
    formula: ({ skillLevel }) => 100 + skillLevel * 30,
  },
  'AS_SONICBLOW': {
    name: 'AS_SONICBLOW',
    isMatk: false,
    isMelee: true,
    element: ElementType.Neutral,
    hit: 1,
    totalHit: 8,
    formula: ({ skillLevel }) => skillLevel * 50,
  },
  'KN_BOWLINGBASH': {
    name: 'KN_BOWLINGBASH',
    isMatk: false,
    isMelee: true,
    element: ElementType.Neutral,
    hit: 1,
    totalHit: 1,
    formula: ({ skillLevel }) => 100 + skillLevel * 40,
  },
  'AC_DOUBLE': {
    name: 'AC_DOUBLE',
    isMatk: false,
    isMelee: false,
    element: ElementType.Neutral,
    hit: 1,
    totalHit: 2,
    formula: ({ skillLevel }) => 90 + skillLevel * 10,
  },
  'AL_HEAL': {
    name: 'AL_HEAL',
    isMatk: true,
    isMelee: false,
    element: ElementType.Holy,
    hit: 1,
    totalHit: 1,
    formula: ({ skillLevel, baseLevel }) => skillLevel * 10 * (baseLevel / 100),
  },
  'RK_SONICWAVE': {
    name: 'RK_SONICWAVE',
    isMatk: false,
    isMelee: false,
    element: ElementType.Neutral,
    hit: 1,
    totalHit: 1,
    formula: ({ skillLevel, baseLevel }) => (1050 + skillLevel * 150) * (baseLevel / 100),
  },
  'Runic Explosion': {
    name: 'Runic Explosion',
    isMatk: false,
    isMelee: true,
    element: null,
    hit: 1,
    totalHit: 1,
    canCri: true,
    criDmgPercentage: 1,
    linkedSkill: 'RK_RUNEMASTERY',
    formula: ({ skillLevel, baseLevel, str }) => (skillLevel + (str || 0) / 5.7) * 100 * (baseLevel / 100),
  },
  'WZ_EARTHSPIKE': {
    name: 'WZ_EARTHSPIKE',
    isMatk: true,
    isMelee: false,
    element: ElementType.Earth,
    hit: 1,
    totalHit: 1,
    formula: ({ skillLevel }) => skillLevel * 100,
  },
  'HW_NAPALMVULCAN': {
    name: 'HW_NAPALMVULCAN',
    isMatk: true,
    isMelee: false,
    element: ElementType.Ghost,
    hit: 1,
    totalHit: 1,
    formula: ({ skillLevel, baseLevel }) => skillLevel * 70 * (baseLevel / 100),
  },
  'SO_PSYCHIC_WAVE': {
    name: 'SO_PSYCHIC_WAVE',
    isMatk: true,
    isMelee: false,
    element: ElementType.Neutral,
    hit: 1,
    totalHit: 1,
    formula: ({ skillLevel, baseLevel, int }) => (skillLevel * 70 + (int || 0) * 3) * (baseLevel / 100),
  },
  'GC_CROSSIMPACT': {
    name: 'GC_CROSSIMPACT',
    isMatk: false,
    isMelee: true,
    element: ElementType.Neutral,
    hit: 1,
    totalHit: 7,
    formula: ({ skillLevel, baseLevel }) => (1150 + skillLevel * 400) * (baseLevel / 100),
  },
  'RK_IGNITIONBREAK': {
    name: 'RK_IGNITIONBREAK',
    isMatk: false,
    isMelee: true,
    element: ElementType.Fire,
    hit: 1,
    totalHit: 1,
    formula: ({ skillLevel, baseLevel }) => skillLevel * 450 * (baseLevel / 100),
  },
  'WL_CRIMSONROCK': {
    name: 'WL_CRIMSONROCK',
    isMatk: true,
    isMelee: false,
    element: ElementType.Fire,
    hit: 1,
    totalHit: 1,
    formula: ({ skillLevel, baseLevel }) => (700 + skillLevel * 600) * (baseLevel / 100),
  },
  'WL_JACKFROST': {
    name: 'WL_JACKFROST',
    isMatk: true,
    isMelee: false,
    element: ElementType.Water,
    hit: 1,
    totalHit: 1,
    formula: ({ skillLevel, baseLevel }) => (800 + skillLevel * 500) * (baseLevel / 100),
  },
  'WL_CHAINLIGHTNING': {
    name: 'WL_CHAINLIGHTNING',
    isMatk: true,
    isMelee: false,
    element: ElementType.Wind,
    hit: 1,
    totalHit: 1,
    formula: ({ skillLevel, baseLevel }) => (500 + skillLevel * 100) * (baseLevel / 100),
  },
  'WL_EARTHSTRAIN': {
    name: 'WL_EARTHSTRAIN',
    isMatk: true,
    isMelee: false,
    element: ElementType.Earth,
    hit: 1,
    totalHit: 1,
    formula: ({ skillLevel, baseLevel }) => (1000 + skillLevel * 600) * (baseLevel / 100),
  },
  'GN_CART_TORNADO': {
    name: 'GN_CART_TORNADO',
    isMatk: false,
    isMelee: true,
    element: ElementType.Neutral,
    hit: 1,
    totalHit: 1,
    formula: ({ skillLevel }) => skillLevel * 200,
  },
  'CG_ARROWVULCAN': {
    name: 'CG_ARROWVULCAN',
    isMatk: false,
    isMelee: false,
    element: ElementType.Neutral,
    hit: 1,
    totalHit: 1,
    formula: ({ skillLevel, baseLevel }) => (skillLevel * 150 + 100) * (baseLevel / 100),
  },
  'GS_SPREADATTACK': {
    name: 'GS_SPREADATTACK',
    isMatk: false,
    isMelee: false,
    element: ElementType.Neutral,
    hit: 1,
    totalHit: 1,
    formula: ({ skillLevel }) => skillLevel * 200,
  },
  'Spiral Pierce': {
    name: 'Spiral Pierce',
    isMatk: false,
    isMelee: true,
    element: ElementType.Neutral,
    hit: 1,
    totalHit: 5,
    formula: ({ skillLevel }) => skillLevel * 50 + 150,
  },
  'PA_PRESSURE': {
    name: 'PA_PRESSURE',
    isMatk: false,
    isMelee: false,
    element: ElementType.Holy,
    hit: 1,
    totalHit: 1,
    formula: ({ skillLevel }) => skillLevel * 200,
  },
  'AB_JUDEX': {
    name: 'AB_JUDEX',
    isMatk: true,
    isMelee: false,
    element: ElementType.Holy,
    hit: 1,
    totalHit: 1,
    formula: ({ skillLevel, baseLevel }) => (skillLevel * 100 + 200) * (baseLevel / 100),
  },
  'Fatal Menace': {
    name: 'Fatal Menace',
    isMatk: false,
    isMelee: true,
    element: ElementType.Neutral,
    hit: 1,
    totalHit: 1,
    formula: ({ skillLevel, baseLevel, agi }) => (skillLevel * 120 + (agi || 0) * 2) * (baseLevel / 100),
  },
  'SU_LUNATICCARROTBEAT': {
    name: 'SU_LUNATICCARROTBEAT',
    isMatk: false,
    isMelee: true,
    element: null,
    hit: 3,
    totalHit: 3,
    formula: ({ skillLevel, baseLevel, str }) => (200 + skillLevel * 100 + (str || 0) * 5) * (baseLevel / 100),
  },
  'SJ_FLASHKICK': {
    name: 'SJ_FLASHKICK',
    isMatk: false,
    isMelee: true,
    element: ElementType.Neutral,
    hit: 1,
    totalHit: 1,
    formula: ({ skillLevel, baseLevel }) => (100 + skillLevel * 100) * (baseLevel / 100),
  },
};
